version: '3'

services:
  serviciospublicos:
    image: rafaelreyes/serviciospublicos
    hostname: service
    ports:
      - 8080:8080
    netwok_mode: "host"
    volumes:
      - .:/code/seviciospublicos
    networks:
    modval_net:
      ipv4_address: '192.168.1.101'
  routing:
    image: juanrgs/routing
    build: ./routing
    hostname: routing
    ports:
      - 9002:80
    netwok_mode: "host"
    volumes:
      - .:/code/routing
    networks:
    modval_net:
      ipv4_address: '192.168.1.102'
  dispatcher:
    image: heysson/conveniodispatcher
    build: ./conveniodispatcher
    hostname: dispacher
    ports:
      - 9003:80
    netwok_mode: "host"
    volumes:
      - .:/code/conveniodispatcher
    networks:
    modval_net:
      ipv4_address: '192.168.1.102'
      

networks:
  modelado_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
