version: '3'

services:
  serviciospublicos:
    image: rafaelreyes/serviciospublicos    
    ports:
      - 8080:8080
    volumes:
      - .:/code/seviciospublicos
  routing:
    image: juanrgs/routing
    build: ./routing
    ports:
      - 9002:80
    volumes:
      - .:/code/routing
  dispatcher:
    image: heysson/conveniodispatcher
    build: ./conveniodispatcher
    ports:
      - 9003:80
    volumes:
      - .:/code/conveniodispatcher
